<#ftl strip_whitespace="true">
<#assign importList = [] />
package org.genevaers.repository.components;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

<#--- Get a list of unique enum entries to be imported --->
<#list component.members as member>
    <#if member.importString ?? && ! importList?seq_contains(member.importString)>
        <#assign importList = importList + [member.importString] />
    </#if>
</#list>
<#list importList?sort as i>
${i}
</#list>

/**
 * This class was automatically generated by the GenevaERS Component Generator.
 * 
 * DO NOT EDIT
 * 
 */
public class ${component.componentName} extends ComponentNode
{
    private static final Map<String, String> DISPLAY_NAMES;

    static {
        Map<String, String> map = new HashMap<>();
<#list component.members as member>
<#if member.displayName??>
        map.put("${member.name}", "${member.displayName}");
</#if>
</#list>
        DISPLAY_NAMES = Collections.unmodifiableMap(map);
    }

    public static Map<String, String> getDisplayNames() {
        return DISPLAY_NAMES;
    }

<#list component.members as member>
${member.fieldEntry}
</#list>

<#list component.members as member>
${member.getAndSetEntry}
</#list>
}
