<#ftl strip_whitespace="true">
<#assign importList = [] />
<#assign javaList = false />
package org.genevaers.engine.extractor;

import java.io.FileWriter;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.genevaers.engine.lookups.Join;
import org.genevaers.engine.lookups.JoinsRepo;
import org.genevaers.genevaio.ltfile.LTRecord;
import org.genevaers.genevaio.recordreader.FileRecord;
import org.genevaers.genevaio.recordreader.RecordFileWriter;
import org.genevaers.utilities.GersCodePage;
import com.google.common.flogger.FluentLogger;

/**
 * This class was automatically generated by the GenevaERS Extract Generator.
 * 
 * DO NOT EDIT
 * 
 */
 
public class XLT extends Extract {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    public XLT() {
//Input DD names ${inputdds?size}
<#if inputdds?size gt 0>
<#list inputdds as ip>
        inputDDnames.add("${ip}");
</#list>
</#if>
<#if joins?size gt 0>
<#list joins as j>
        JoinsRepo.addJoin(new Join("${j.newid}", ${j.targetLf?c}, ${j.targetLr?c}, ${j.recLength}, ${j.keyLength}, ${j.fileid}));
</#list>
<#else>
        // No joins defined for this extract
</#if>
    }

    public void processRecord(byte[] src, ByteBuffer target, RecordFileWriter outWriter, int numrecords) {
        FileRecord joinBuffer = null;
        Join jn;
<#if filterRecs?size gt 4>
// Filter Logic
<#list filterRecs as rec>
${rec}
</#list>
<#else>
        // No filter logic defined for this extract 
        columnLogic(src, target, outWriter, numrecords);
</#if>
    }

// Column Logic
    public void columnLogic(byte[] src, ByteBuffer target, RecordFileWriter outWriter, int numrecords) {
        FileRecord joinBuffer = null;
        Join jn;
<#list columnRecs as rec>
${rec}
</#list>
    }

    public int getOutputLen() {
        return  ${outLen};
    }

    public int getLrLen() {
        return  ${lrLen};
    }


}
