<#ftl strip_whitespace="true">
<#assign importList = [] />
<#assign javaList = false />
package org.genevaers.engine.extractor;

import java.io.FileWriter;
import java.io.UnsupportedEncodingException;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.genevaers.engine.lookups.Join;
import org.genevaers.engine.lookups.JoinsRepo;
import org.genevaers.genevaio.ltfile.LTRecord;
import org.genevaers.genevaio.recordreader.FileRecord;
import org.genevaers.genevaio.recordreader.RecordFileWriter;
import org.genevaers.utilities.GersCodePage;
import org.genevaers.utilities.GersConfigration;
import com.google.common.flogger.FluentLogger;
import com.ibm.jzos.fields.AssemblerDatatypeFactory;
import com.ibm.jzos.fields.BinaryAsIntField;
import com.ibm.jzos.fields.ByteArrayField;
import com.ibm.jzos.fields.PackedDecimalAsBigDecimalField;
import com.ibm.jzos.fields.PackedDecimalAsIntField;
import com.ibm.jzos.fields.StringField;

import org.genevaers.engine.runcolumns.*;

/**
 * This class was automatically generated by the GenevaERS Extract Generator.
 * 
 * DO NOT EDIT
 * 
 */
 
public class PECode extends Extract {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();
    protected static AssemblerDatatypeFactory factory = new AssemblerDatatypeFactory();
//Source LR Fields
<#list srcdefs as def>
    ${def};
</#list>

    static {
        factory.setOffset(0);
    }

//Column Fields
<#list coldefs as coldef>
    ${coldef};
</#list>

//Lookup Fields
<#list lkfdefs as lkfdef>
    ${lkfdef};
</#list>

    public PECode() {
//Input DD names ${inputdds?size}
<#if inputdds?size gt 0>
<#list inputdds as ip>
        inputDDnames.add("${ip}");
</#list>
</#if>
<#if joins?size gt 0>
<#list joins as j>
        JoinsRepo.addJoin(new Join("${j.newid}", ${j.targetLf?c}, ${j.targetLr?c}, ${j.recLength}, ${j.keyLength}, ${j.fileid}));
</#list>
<#else>
        // No joins defined for this extract
</#if>
    }

    public void processRecord(byte[] src, byte[] target, RecordFileWriter outWriter, int numrecords) {
        Join jn;
<#if filterRecs?size gt 4>
// Filter Logic
<#list filterRecs as rec>
${rec}
</#list>
<#else>
        // No filter logic defined for this extract 
        columnLogic(src, target, outWriter, numrecords);
</#if>
    }

// Column Logic
    public void columnLogic(byte[] src, byte[] target, RecordFileWriter outWriter, int numrecords) {
        DirectColumn.setSource(src);
        DirectColumn.setTarget(target);
        Join jn;
<#list columnRecs as rec>
${rec}
</#list>
    }

    public int getOutputLen() {
        return  ${outLen};
    }

    public int getLrLen() {
        return  ${lrLen};
    }


}
